---
- name: configure redhat machines
  hosts: redhat
  become: yes
  tasks:
    - name: update repos
      yum:
        update_cache: yes
    - name: install tools
      yum:
        name: nmap
        state: present
      yum:
        name: ufw.noarch
        state: present
      yum:
        name: tmux.x86_64
        state: present
      yum:
        name: tcpdump.x86_64
        state: present
      yum:
        name: lynis.noarch
        state: present
      yum:
        name: clamav.x86_64
        state: present
      yum: 
        name: nikto.noarch
        state: present
    # - name: run rh.sh to remote machines
    #   script: ../Scripts/Shell/rh.sh
    - name: configure local firewall
      ufw:
        state: reset
      ufw:
        rule: allow
        port: 22
        proto: tcp
      ufw:
        rule: allow
        port: 80
        proto: tcp
      ufw:
        rule: allow
        port: 443
        proto: tcp
      ufw:
        state: enabled